'use client';
import { ContentShell } from '@/components/present/content/ContentShell';
export default function Page() {
  return (
    <ContentShell title="Terms of Service" eyebrow="Legal">
      <p>These terms govern wholesale purchases. Approved trade accounts agree to MAP pricing where applicable, minimum order quantities, and payment terms as configured for their tier. Title passes on shipment.</p>
      <p className="mt-4">This is a demonstration storefront generated by WizDesigner; final terms are configured per customer in WizOrder.</p>
    </ContentShell>
  );
}
